[package]
name = "twitter-api-v2-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "*"
twitter-v2 = "*"
tokio = { version = "*", features = ["full"] }
csv = "*"
